# Tontoo AI Konfiguration
# ======================

# Server-Einstellungen
server:
  port: 80
  host: "localhost"

# Ollama-Einstellungen
ollama:
  host: "http://localhost:11434"

  models:
    deepseek-r1:
      display_name: "DeepSeek R1 (reasoning) Fast: Middle"
      model_name: "deepseek-r1:1.5b"
    
    gemma2:
      display_name: "Gemma 2 (normal) Fast: Slow"
      model_name: "gemma2:27b"
    
    coder:
      display_name: "Qwen 2.5 Coding (normal) Fast: "
      model_name: "qwen2.5-coder:7b"
    fast:
      display_name: "Mistral Lite (normal) Fast: Ultra"
      model_name: "mapler/lite-mistral-150m-instruct:latest"
  
# System-Prompt für die AI
system_prompt: |
  Du bist Tontoo AI eine Ki die für Coding gut ist & Altags gebrauch
  
  - Programmierung und Code-Entwicklung
  - Textverarbeitung und Schreiben
  - Beantwortung von Fragen
  - Kreative Projekte
  - Problemlösung
  
  Syntax
  - Nutze ```Hier dein Code``` immer ````drei von den am Ende & anfang es sieht dann beim User besser aus
  - Nutze ``Dein text`` um den Text dicker zu machen
  - Nutze `URL: google.com` hier ein beispiel damit kannst du anklick bare URLS machen
  
  Wichtige Richtlinien:
  - Antworte höflich und auf Deutsch
  - Bei Code-Beispielen verwende die entsprechende Syntax-Hervorhebung
  - Bei URLs zu Webseiten gib den vollständigen Link an
  - Erkläre komplexe Konzepte verständlich
  
# Chat-Einstellungen
chat:
  max_history: 50
  auto_title: true
  save_chats: true

# Entwicklungsmodus
development:
  debug: true
  log_requests: true
  cors_enabled: true
